models/avatar.py
import dicebear
from dicebear import DOptions


class Avatar(dicebear.DAvatar):

    def __init__(self, style: str, seed: str, options: dict):
        stock_options = dict((k, v) for k, v in options.items() if k in dicebear.models.default_options)
        custom_options = dict((k, v) for k, v in options.items() if k not in dicebear.models.default_options)
        super().__init__(style, seed, options=DOptions(**options), custom=custom_options)

    def __str__(self):
        return self.url_svg

models/event.py
import datetime
import os
import json
import sys
from typing import Set, Optional

import dateparser
import pytz
from tzlocal import get_localzone

from models.challenge import Challenge
from models.challengecategory import ChallengeCategory
from models.config import Config
from models.flag_manager import FlagManager


class Event:
    def __init__(self, name: str, categories: Set[ChallengeCategory], scope_html_path: str, logo: Optional[bytes] = None,
                 start_date: Optional[datetime.datetime] = None, end_date: Optional[datetime.datetime] = None,
                 splash: Optional[bytes] = None, splash_border: Optional[str] = None):
        self.__name: str = name
        self.__categories: Set[ChallengeCategory] = categories
        self.__flag_manager: FlagManager = FlagManager(self)
        self.__logo: Optional[bytes] = logo
        self.__scope_html_path: str = scope_html_path
        self.__start_date: Optional[datetime.datetime] = start_date
        self.__end_date: Optional[datetime.datetime] = end_date
        self.__splash: Optional[bytes] = splash
        self.__splash_border: Optional[str] = splash_border

    @property
    def name(self) -> str:
        return self.__name

    @property
    def start_date(self) -> Optional[datetime.datetime]:
        return self.__start_date

    @property
    def end_date(self) -> Optional[datetime.datetime]:
        return self.__end_date

    @property
    def has_started(self) -> Optional[bool]:
        if self.start_date is None:
            return None
        now = datetime.datetime.now()
        return self.start_date <= now.replace(tzinfo=now.tzinfo or get_localzone())

    @property
    def has_ended(self) -> Optional[bool]:
        if self.end_date is None:
            return None
        now = datetime.datetime.now()
        return self.end_date <= now.replace(tzinfo=now.tzinfo or get_localzone())

    @property
    def scope_html(self) -> Optional[str]:
        if os.path.isfile(self.__scope_html_path):
            f = open(self.__scope_html_path, 'r')
            html = f.read()
            f.close()
            return html
        return None

    @property
    def categories(self) -> Set[ChallengeCategory]:
        return self.__categories

    @property
    def challenges(self) -> Set[Challenge]:
        return set().union(*(c.challenges for c in self.categories))

    def get_challenge(self, challenge_slug: str) -> Optional[Challenge]:
        for challenge in self.challenges:
            if challenge.slug == challenge_slug:
                return challenge
        return None

    @property
    def flag_manager(self) -> FlagManager:
        return self.__flag_manager

    @property
    def secret_key(self) -> str:
        master_key = Config.get_config().secret_key
        return master_key[len(master_key) // 2:]

    @staticmethod
    def from_directory(directory: str) -> 'Event':
        if not os.path.isdir(directory) or not os.path.isfile(os.path.join(directory, 'name')):
            raise FileNotFoundError()

        f = open(os.path.join(directory, 'name'), 'r')
        name = f.read().strip()
        f.close()

        logo: Optional[bytes] = None
        if os.path.isfile(os.path.join(directory, 'logo')):
            f = open(os.path.join(directory, 'logo'), 'rb')
            logo = f.read()
            f.close()

        splash: Optional[bytes] = None
        if os.path.isfile(os.path.join(directory, 'splash')):
            f = open(os.path.join(directory, 'splash'), 'rb')
            splash = f.read()
            f.close()

        splash_border: Optional[str] = None
        if os.path.isfile(os.path.join(directory, 'splash_border')):
            f = open(os.path.join(directory, 'splash_border'), 'r')
            splash_border = f.read().strip()
            f.close()

        start_date: Optional[datetime.datetime] = None
        if os.path.isfile(os.path.join(directory, 'start_date')):
            f = open(os.path.join(directory, 'start_date'), 'r')
            start_date = dateparser.parse(f.read())
            if start_date.tzinfo is None:
                local_timezone = pytz.timezone('local')
                start_date = start_date.replace(tzinfo=local_timezone)
            f.close()

        end_date: Optional[datetime.datetime] = None
        if os.path.isfile(os.path.join(directory, 'end_date')):
            f = open(os.path.join(directory, 'end_date'), 'r')
            end_date = dateparser.parse(f.read())
            if end_date.tzinfo is None:
                local_timezone = pytz.timezone('local')
                end_date = end_date.replace(tzinfo=local_timezone)
            f.close()

        scope_html_path: str = os.path.abspath(os.path.join(directory, 'scope.html'))

        categories: Set[ChallengeCategory] = set()
        challenges: Set[Challenge] = set()
        if os.path.isdir(os.path.join(directory, 'challenges')):
            for category_slug in os.listdir(os.path.join(directory, 'challenges')):
                if not os.path.isdir(os.path.join(directory, 'challenges', category_slug)):
                    continue
                category = ChallengeCategory.from_directory(os.path.join(directory, 'challenges', category_slug))
                assert not any(category.slug == c.slug for c in categories)
                categories.add(category)
                for challenge_slug in os.listdir(os.path.join(directory, 'challenges', category_slug)):
                    if not os.path.isdir(os.path.join(directory, 'challenges', category_slug, challenge_slug)):
                        continue
                    challenge = Challenge.from_directory(os.path.join(directory, 'challenges', category_slug, challenge_slug), category=category)
                    assert not any(challenge.slug == c.slug for c in challenges)
                    category.add_challenge(challenge)
                    challenges.add(challenge)
        else:
            sys.stderr.write("Warning: could not find challenges directory\n")

        return Event(name, categories, scope_html_path, logo, start_date, end_date, splash, splash_border)

    @property
    def logo(self) -> Optional[bytes]:
        return self.__logo

    @property
    def splash(self) -> Optional[bytes]:
        return self.__splash

    @property
    def splash_border(self) -> Optional[str]:
        return self.__splash_border

routes.py
import base64
import json
import mimetypes
import sys
from datetime import datetime, timedelta
from json import JSONDecodeError
from typing import List, Dict, Union

import dicebear.models
# noinspection PyUnresolvedReferences
import pylibmagic  # don't remove, required for cross-platform python-magic support
import magic
import pytz
import requests
import sqlalchemy
from dicebear import DOptions
from flask import Blueprint, send_from_directory, render_template, redirect, url_for, request, abort, Response
from flask import current_app as app
from flask_login import current_user, login_required
from flask_wtf.csrf import generate_csrf
from requests import ReadTimeout
from tzlocal import get_localzone
from werkzeug.exceptions import BadRequest
import hmac
import hashlib

from models.ctf_platform_app import CTFPlatformApp
from db import db
from models.config import Config
from models.orchestration_static import OrchestrationStatic
from models.solve import Solve
from models.team import Team
from models.user import User

app: CTFPlatformApp

main_blueprint = Blueprint('main', __name__)


@main_blueprint.route('/static/<path:path>')
def static(path):
    return send_from_directory('static', path)


@main_blueprint.route('/dashboard')
@login_required
def dashboard():
    latest_solves: List[Solve] = Solve.query.order_by(Solve.when.desc()).limit(15)

    # get values for graph
    team_points: Dict[str, List[Dict[str, Union[str, int]]]] = {}
    teams = Team.query.all()
    for team in teams:
        points: List[Dict[str, Union[str, int]]] = []
        if app.event.start_date is not None and not any(s.when.replace(tzinfo=s.when.tzinfo or get_localzone()) <= app.event.start_date for s in team.solves):
            points.append({
                'when': app.event.start_date.isoformat(),
                'value': 0})
        for solve in sorted(team.solves, key=lambda s: s.when):
            if len(points) == 0:
                points.append({
                    'when': solve.when.isoformat(),
                    'value': solve.points})
            else:
                points.append({
                    'when': solve.when.isoformat(),
                    'value': points[-1]['value'] + solve.points})
        points.append({
            'when': datetime.now().isoformat(),
            'value': team.points})
        team_points[team] = points

    return render_template('dashboard.html', latest_solves=latest_solves, team_points=team_points, teams_ranked=sorted(teams, key=lambda t: t.points, reverse=True))


@main_blueprint.route('/account')
@login_required
def account():
    return render_template('account.html')


@main_blueprint.route('/account/avatar', methods=['POST'])
def avatar():
    if 'style' not in request.form or 'seed' not in request.form or 'options' not in request.form:
        raise BadRequest

    j = {}
    try:
        j = json.loads(request.form['options'])
    except JSONDecodeError:
        raise BadRequest

    current_user.edit_avatar(style=request.form['style'], seed=request.form['seed'], options=j)
    db.session.commit()
    return Response(json.dumps({'avatar': str(current_user.avatar), 'csrf': generate_csrf()}), status=200,
                    mimetype='application/json')


@main_blueprint.route('/')
def index():
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    return redirect(url_for('auth.login'))


@main_blueprint.route('/scope')
@login_required
def scope():
    if app.event.scope_html is None:
        abort(404)
    return render_template('scope.html')


@main_blueprint.route('/team')
@login_required
def team():
    return render_template('team.html', get_solve=lambda t, c: Solve.query.get((t.slug, c.slug)))


@main_blueprint.route('/team/leave', methods=['POST'])
@login_required
def leave_team():
    if current_user.team is None:
        abort(404)
    else:
        old_team = current_user.team
        current_user.team = None
        current_user.team_pending = False
        db.session.commit()
        if len(old_team.users) == 1 and old_team.users[0].team_pending:
            old_team.users[0].team_pending = False
            db.session.commit()
        if current_user.team is not None:
            abort(500)
    return Response(json.dumps({}), status=200, mimetype='application/json')


@main_blueprint.route('/team/reject', methods=['POST'])
@login_required
def team_reject():
    if 'username' not in request.form:
        abort(400)
    if current_user.team is None:
        abort(404)
    if current_user.team_pending:
        abort(403)
    user = User.query.get(request.form['username'])
    if user is None or not user.team_pending:
        abort(404)
    if current_user.team != user.team:
        abort(403)
    user.team = None
    user.team_pending = False
    db.session.commit()
    return Response(json.dumps({}), status=200, mimetype='application/json')


@main_blueprint.route('/team/join', methods=['POST'])
@login_required
def join_team():
    if 'slug' not in request.form:
        abort(400)
    if current_user.team is not None:
        abort(403)
    new_team = Team.query.get(request.form['slug'])
    if new_team is None:
        abort(404)
    current_user.team_pending = len(new_team.users) > 0
    current_user.team = new_team
    db.session.commit()
    return Response(json.dumps({}), status=200, mimetype='application/json')


@main_blueprint.route('/team/join/<string:slug>', methods=['GET'])
@login_required
def join_team_get(slug: str):
    if current_user.team is not None:
        abort(403)
    new_team = Team.query.get(slug)
    if new_team is None:
        abort(404)
    current_user.team_pending = len(new_team.users) > 0
    current_user.team = new_team
    db.session.commit()
    return redirect(url_for('main.team'))


@main_blueprint.route('/team/approve', methods=['POST'])
@login_required
def team_approve():
    if 'username' not in request.form:
        abort(400)
    if current_user.team is None:
        abort(404)
    if current_user.team_pending:
        abort(403)
    user = User.query.get(request.form['username'])
    if user is None or not user.team_pending:
        abort(404)
    if current_user.team != user.team:
        abort(403)
    user.team_pending = False
    db.session.commit()
    return Response(json.dumps({}), status=200, mimetype='application/json')


@main_blueprint.route('/team/create', methods=['POST'])
@login_required
def create_team():
    if 'name' not in request.form:
        abort(400)
    if current_user.team is not None:
        abort(403)
    new_team = Team(name=request.form['name'])
    db.session.add(new_team)
    current_user.team = new_team
    try:
        db.session.commit()
    except sqlalchemy.exc.IntegrityError:
        abort(403)  # not unique
    # begin orchestrate
    config = Config.get_config()
    for challenge in app.event.challenges:
        static_orch = OrchestrationStatic.query.get((new_team.slug, challenge.slug))
        if static_orch is None:
            static_orch = OrchestrationStatic(new_team, challenge)
            db.session.add(static_orch)
            db.session.commit()
        if config.orchestrator_ip is None:
            sys.stderr.write(
                "Cannot deploy {challenge.slug} for {team.slug}: No orchestrator_ip set in config table of DB!\n")
        else:
            url = f"http://{Config.get_config().orchestrator_ip}:{Config.get_config().orchestrator_port}/orchestrate/static"
            try:
                requests.post(
                    url,
                    json={'team': new_team.slug, 'challenge': challenge.slug},
                    timeout=(None, 0.1))
            except ReadTimeout:
                pass
            sys.stderr.write(f"Requested static deploy of {challenge.slug} for {new_team.slug} via {url}\n")
    return Response(json.dumps({}), status=200, mimetype='application/json')


@main_blueprint.route('/team/size')
@login_required
def team_size():
    if current_user.team is None:
        abort(403)
    return str(len(current_user.team.users))


@main_blueprint.route('/challenge/<string:challenge_slug>', methods=['GET', 'POST'])
@login_required
def challenge(challenge_slug: str):
    c = app.event.get_challenge(challenge_slug)
    if c is None:
        abort(404)
    if request.method == 'POST':
        if 'flag' not in request.form:
            abort(400)
        if app.event.has_ended is not None and app.event.has_ended:
            return Response("The event has ended! You can't submit any more flags.", status=403,
                            mimetype='text/plain')
        if current_user.team is None or current_user.team_pending:
            return Response("You need to be accepted onto a team before you can submit flags.", status=403,
                            mimetype='text/plain')
        if current_user.team.has_solved(c):
            return Response("Your team has already solved this flag.", status=410, mimetype='text/plain')
        if app.event.flag_manager.verify_flag(c, current_user.team, request.form['flag']):
            # get multiplier
            solve_position = len(c.solves) + 1
            new_solve = Solve(current_user.team, current_user, c, datetime.now(), Solve.calculate_multiplier(solve_position))
            db.session.add(new_solve)
            db.session.commit()
            return Response(json.dumps({}), status=200, mimetype='application/json')
        return Response("Incorrect flag", status=402, mimetype='text/plain')
    else:
        return render_template('challenge.html', challenge=c,
                               orch_static=OrchestrationStatic.query.get((current_user.team.slug if current_user.team is not None else None, c.slug)),
                               calculate_multiplier=Solve.calculate_multiplier)


@main_blueprint.route('/challenges')
@login_required
def challenges():
    return render_template('challenges.html')


@main_blueprint.route('/logo')
def logo():

templates/widgets/auth-right.html
<div id="auth-right"
     style="{%- if event.splash is not none -%}background-image:url('{{ url_for('main.splash') }}')!important;{%- if event.splash_border is not none -%}border:{{ event.splash_border }};{%- endif -%}"{%- endif -%}>
</div>

templates/widgets/avatar.html
<div class="avatar avatar-{{ size }}{% if editable is defined and editable %} editable{% endif %}">
{%- if editable is defined and editable %}
    <div>
        Edit
    </div>
{% endif -%}
{%- if not(editable is defined and editable) %}
    <div>
{%- endif -%}
        <img src="{{ user.avatar }}" alt="Avatar">
    {%- if user.is_admin %}
        <span class="avatar-status bg-primary" data-bs-toggle="tooltip" data-bs-placement="top" title="Admin"></span>
    {% endif -%}
{%- if not(editable is defined and editable) %}
    </div>
{%- endif -%}
</div>

templates/widgets/logo.html
{%- if event.logo is none -%}
    {{ event.name }}
{%- else -%}
    <img src="{{ url_for('main.logo') }}" alt="Logo" srcset="" style="height:initial!important;width:90%">
{%- endif -%}

templates/widgets/team-members-card.html
{%- do styles.append(url_for('static', filename='assets/extensions/sweetalert2/sweetalert2.min.css')) -%}
{%- do scripts.append(url_for('static', filename='assets/extensions/sweetalert2/sweetalert2.min.js')) -%}
{%- do scripts.append(url_for('static', filename='assets/toast.js')) -%}
{%- do pre_content_scripts.append('https://code.jquery.com/jquery-3.7.1.min.js') %}
{%- do scripts.append(url_for('static', filename='assets/team.js')) -%}
<div class="card">
{%- if current_user.team is none -%}
        <div class="card-content py-3">
            <div class="px-4">
                <a href="{{ url_for('main.team') }}" class="btn btn-block btn-xl btn-warning font-bold">
                    Join or Create a Team
                </a>
            </div>
        </div>
    {%- else -%}
        <div class="card-header">
            <h4>Team Members</h4>
        </div>
        <div class="card-content pb-4">
            {%- for team_member in current_user.team.users -%}
                {%- if team_member.team_pending -%}
                    <div class="d-flex align-items-start px-4 py-3 text-bg-warning">
                {%- elif team_member == current_user -%}
                    <div class="d-flex align-items-start px-4 py-3 text-bg-primary">
                {%- else -%}
                    <div class="d-flex align-items-start px-4 py-3">
                {%- endif -%}
            {% with size='lg', user=team_member %}
                {% include 'widgets/avatar.html' %}
            {% endwith %}
                <div class="name ms-4 flex-grow-1">
                    <h5 class="mb-1{%- if team_member == current_user and not current_user.team_pending %} text-light{%- endif -%}">{{ team_member.username }}</h5>
                    {%- if team_member.team_pending -%}
                        <h6 class="mb-0">Pending approval</h6>
                    {%- else -%}
                        <h6 class="text-body-secondary mb-0">{{ team_member.solves|length }} solve{%- if team_member.solves|length != 1 -%}s{%- endif %} // {{ team_member.points }} points</h6>
                    {%- endif -%}
                </div>
                <div class="ms-4">
                    {%- if team_member.team_pending and not current_user.team_pending -%}
                        <div class="btn-group" role="group">
                            <button type="button" class="btn btn-lg btn-danger reject-member" title="Reject"
                                    aria-label="Reject" data-username="{{ team_member.username }}"><i class="bi bi-x"></i>
                            </button>
                            <button type="button" class="btn btn-lg btn-success approve-member" title="Approve"
                                    aria-label="Approve" data-username="{{ team_member.username }}"><i
                                    class="bi bi-check"></i></button>
                        </div>
                    {%- endif -%}
                </div>
            </div>
            {%- endfor -%}
            <div class="px-4">
                <button class="btn btn-block btn-xl btn-outline-primary font-bold mt-3 invite-member"
                        {%- if current_user.team_pending %} disabled{%- endif -%}>Invite Member
                </button>
                <script>
                    var teamSlug = "{{ current_user.team.slug }}";
                    var currentURL = new URL(window.location.href);
                    var teamJoinURL = currentURL.protocol + "//" + currentURL.host + "{{ url_for('main.join_team_get', slug=current_user.team.slug) }}";
                    var approveMemberEndpoint = "{{ url_for('main.team_approve') }}";
                    var approveMemberCSRFToken = "{{ csrf_token() }}";
                    var approveMemberCSRFName = "{{ config.WTF_CSRF_FIELD_NAME }}";
                    var rejectMemberEndpoint = "{{ url_for('main.team_reject') }}";
                    var rejectMemberCSRFToken = "{{ csrf_token() }}";
                    var rejectMemberCSRFName = "{{ config.WTF_CSRF_FIELD_NAME }}";
                </script>
            </div>
        </div>
    {%- endif -%}
</div>