routes.py
import base64
import json
import mimetypes
import sys
from datetime import datetime, timedelta
from json import JSONDecodeError
from typing import List, Dict, Union

import dicebear.models
# noinspection PyUnresolvedReferences
import pylibmagic  # don't remove, required for cross-platform python-magic support
import magic
import pytz
import requests
import sqlalchemy
from dicebear import DOptions
from flask import Blueprint, send_from_directory, render_template, redirect, url_for, request, abort, Response
from flask import current_app as app
from flask_login import current_user, login_required
from flask_wtf.csrf import generate_csrf
from requests import ReadTimeout
from tzlocal import get_localzone
from werkzeug.exceptions import BadRequest
import hmac
import hashlib

from models.ctf_platform_app import CTFPlatformApp
from db import db
from models.config import Config
from models.orchestration_static import OrchestrationStatic
from models.solve import Solve
from models.team import Team
from models.user import User

app: CTFPlatformApp

main_blueprint = Blueprint('main', __name__)


@main_blueprint.route('/static/<path:path>')
def static(path):
    return send_from_directory('static', path)


@main_blueprint.route('/dashboard')
@login_required
def dashboard():
    latest_solves: List[Solve] = Solve.query.order_by(Solve.when.desc()).limit(15)

    # get values for graph
    team_points: Dict[str, List[Dict[str, Union[str, int]]]] = {}
    teams = Team.query.all()
    for team in teams:
        points: List[Dict[str, Union[str, int]]] = []
        if app.event.start_date is not None and not any(s.when.replace(tzinfo=s.when.tzinfo or get_localzone()) <= app.event.start_date for s in team.solves):
            points.append({
                'when': app.event.start_date.isoformat(),
                'value': 0})
        for solve in sorted(team.solves, key=lambda s: s.when):
            if len(points) == 0:
                points.append({
                    'when': solve.when.isoformat(),
                    'value': solve.points})
            else:
                points.append({
                    'when': solve.when.isoformat(),
                    'value': points[-1]['value'] + solve.points})
        points.append({
            'when': datetime.now().isoformat(),
            'value': team.points})
        team_points[team] = points

    return render_template('dashboard.html', latest_solves=latest_solves, team_points=team_points, teams_ranked=sorted(teams, key=lambda t: t.points, reverse=True))


@main_blueprint.route('/account')
@login_required
def account():
    return render_template('account.html')


@main_blueprint.route('/account/avatar', methods=['POST'])
def avatar():
    if 'style' not in request.form or 'seed' not in request.form or 'options' not in request.form:
        raise BadRequest

    j = {}
    try:
        j = json.loads(request.form['options'])
    except JSONDecodeError:
        raise BadRequest

    current_user.edit_avatar(style=request.form['style'], seed=request.form['seed'], options=j)
    db.session.commit()
    return Response(json.dumps({'avatar': str(current_user.avatar), 'csrf': generate_csrf()}), status=200,
                    mimetype='application/json')


@main_blueprint.route('/')
def index():
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    return redirect(url_for('auth.login'))


@main_blueprint.route('/scope')
@login_required
def scope():
    if app.event.scope_html is None:
        abort(404)
    return render_template('scope.html')


@main_blueprint.route('/team')
@login_required
def team():
    return render_template('team.html', get_solve=lambda t, c: Solve.query.get((t.slug, c.slug)))


@main_blueprint.route('/team/leave', methods=['POST'])
@login_required
def leave_team():
    if current_user.team is None:
        abort(404)
    else:
        old_team = current_user.team
        current_user.team = None
        current_user.team_pending = False
        db.session.commit()
        if len(old_team.users) == 1 and old_team.users[0].team_pending:
            old_team.users[0].team_pending = False
            db.session.commit()
        if current_user.team is not None:
            abort(500)
    return Response(json.dumps({}), status=200, mimetype='application/json')


@main_blueprint.route('/team/reject', methods=['POST'])
@login_required
def team_reject():
    if 'username' not in request.form:
        abort(400)
    if current_user.team is None:
        abort(404)
    if current_user.team_pending:
        abort(403)
    user = User.query.get(request.form['username'])
    if user is None or not user.team_pending:
        abort(404)
    if current_user.team != user.team:
        abort(403)
    user.team = None
    user.team_pending = False
    db.session.commit()
    return Response(json.dumps({}), status=200, mimetype='application/json')


@main_blueprint.route('/team/join', methods=['POST'])
@login_required
def join_team():
    if 'slug' not in request.form:
        abort(400)
    if current_user.team is not None:
        abort(403)
    new_team = Team.query.get(request.form['slug'])
    if new_team is None:
        abort(404)
    current_user.team_pending = len(new_team.users) > 0
    current_user.team = new_team
    db.session.commit()
    return Response(json.dumps({}), status=200, mimetype='application/json')


@main_blueprint.route('/team/join/<string:slug>', methods=['GET'])
@login_required
def join_team_get(slug: str):
    if current_user.team is not None:
        abort(403)
    new_team = Team.query.get(slug)
    if new_team is None:
        abort(404)
    current_user.team_pending = len(new_team.users) > 0
    current_user.team = new_team
    db.session.commit()
    return redirect(url_for('main.team'))


@main_blueprint.route('/team/approve', methods=['POST'])
@login_required
def team_approve():
    if 'username' not in request.form:
        abort(400)
    if current_user.team is None:
        abort(404)
    if current_user.team_pending:
        abort(403)
    user = User.query.get(request.form['username'])
    if user is None or not user.team_pending:
        abort(404)
    if current_user.team != user.team:
        abort(403)
    user.team_pending = False
    db.session.commit()
    return Response(json.dumps({}), status=200, mimetype='application/json')


@main_blueprint.route('/team/create', methods=['POST'])
@login_required
def create_team():
    if 'name' not in request.form:
        abort(400)
    if current_user.team is not None:
        abort(403)
    new_team = Team(name=request.form['name'])
    db.session.add(new_team)
    current_user.team = new_team
    try:
        db.session.commit()
    except sqlalchemy.exc.IntegrityError:
        abort(403)  # not unique
    # begin orchestrate
    config = Config.get_config()
    for challenge in app.event.challenges:
        static_orch = OrchestrationStatic.query.get((new_team.slug, challenge.slug))
        if static_orch is None:
            static_orch = OrchestrationStatic(new_team, challenge)
            db.session.add(static_orch)
            db.session.commit()
        if config.orchestrator_ip is None:
            sys.stderr.write(
                "Cannot deploy {challenge.slug} for {team.slug}: No orchestrator_ip set in config table of DB!\n")
        else:
            url = f"http://{Config.get_config().orchestrator_ip}:{Config.get_config().orchestrator_port}/orchestrate/static"
            try:
                requests.post(
                    url,
                    json={'team': new_team.slug, 'challenge': challenge.slug},
                    timeout=(None, 0.1))
            except ReadTimeout:
                pass
            sys.stderr.write(f"Requested static deploy of {challenge.slug} for {new_team.slug} via {url}\n")
    return Response(json.dumps({}), status=200, mimetype='application/json')


@main_blueprint.route('/team/size')
@login_required
def team_size():
    if current_user.team is None:
        abort(403)
    return str(len(current_user.team.users))


@main_blueprint.route('/challenge/<string:challenge_slug>', methods=['GET', 'POST'])
@login_required
def challenge(challenge_slug: str):
    c = app.event.get_challenge(challenge_slug)
    if c is None:
        abort(404)
    if request.method == 'POST':
        if 'flag' not in request.form:
            abort(400)
        if app.event.has_ended is not None and app.event.has_ended:
            return Response("The event has ended! You can't submit any more flags.", status=403,
                            mimetype='text/plain')
        if current_user.team is None or current_user.team_pending:
            return Response("You need to be accepted onto a team before you can submit flags.", status=403,
                            mimetype='text/plain')
        if current_user.team.has_solved(c):
            return Response("Your team has already solved this flag.", status=410, mimetype='text/plain')
        if app.event.flag_manager.verify_flag(c, current_user.team, request.form['flag']):
            # get multiplier
            solve_position = len(c.solves) + 1
            new_solve = Solve(current_user.team, current_user, c, datetime.now(), Solve.calculate_multiplier(solve_position))
            db.session.add(new_solve)
            db.session.commit()
            return Response(json.dumps({}), status=200, mimetype='application/json')
        return Response("Incorrect flag", status=402, mimetype='text/plain')
    else:
        return render_template('challenge.html', challenge=c,
                               orch_static=OrchestrationStatic.query.get((current_user.team.slug if current_user.team is not None else None, c.slug)),
                               calculate_multiplier=Solve.calculate_multiplier)


@main_blueprint.route('/challenges')
@login_required
def challenges():
    return render_template('challenges.html')


@main_blueprint.route('/logo')
def logo():

templates/tools/avatar-editor.html
{%- do styles.append('https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css') -%}
{%- do styles.append(url_for('static', filename='assets/select2-bootstrap-5-theme.min.css')) -%}
{%- do styles.append('https://cdn.jsdelivr.net/gh/mdbassit/Coloris@latest/dist/coloris.min.css') -%}
{%- do pre_content_scripts.append('https://code.jquery.com/jquery-3.7.1.min.js') %}
{%- do scripts.append('https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js') -%}
{%- do scripts.append('https://cdn.jsdelivr.net/gh/mdbassit/Coloris@latest/dist/coloris.min.js') -%}
{%- do scripts.append(url_for('static', filename='assets/avatar-editor.js')) -%}
<div class="modal fade" id="avatarEditorModal" tabindex="-1">
    <div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Avatar Editor</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                    <div class="input-group mb-3">
                    <label class="input-group-text" for="avatarStyleSelector">Style</label>
                    <select id="avatarStyleSelector" class="form-select"
                            data-existing="{{ current_user.avatar.style }}">
                        {%- for style, meta in dicebear_styles.items() %}
                            <option value="{{ style }}"
                                    data-title="{{ meta.title }}"
                                    data-source="{{ meta.source }}"
                                    data-creator="{{ meta.creator }}"
                                    data-homepage="{{ meta.homepage }}"
                                    data-license-name="{{ meta.license.name }}"
                                    data-license-url="{{ meta.license.url }}"
                            >{{ style|replace('-', ' ')|title }}</option>
                        {%- endfor %}
                    </select>
                </div>
            <div class="row">
                <div class="col-md-4">
                    <table class="mx-auto">
                    <tbody>
                    <tr>
                        <td></td>
                        <td class="avatar-option" id="avatarOptionContainerScale"></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td class="avatar-option" id="avatarOptionContainerTranslateY"></td>
                        <td>
                            <div class="avatar-editor">
                                <div class="avatar avatar-4xl editor">
                                    <div class="spinner">
                                        <div class="spinner-border text-dark"></div>
                                    </div>
                                    <img src="{{ current_user.avatar }}">
                                </div>
                            </div>
                        </td>
                        <td class="avatar-option" id="avatarOptionContainerRotate"></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td class="avatar-option" id="avatarOptionContainerTranslateX"></td>
                        <td class="avatar-option" id="avatarOptionContainerFlip"></td>
                    </tr>
                    </tbody>
                </table>
                </div>
                <div class="col-md-8">
                    <div id="avatarOptions"></div>
                    <button id="avatarSeedRandomise" data-seed="{{ current_user.avatar.seed }}" class="btn btn-primary w-100">
                        <i class="bi bi-dice-2-fill"></i> Roll the Dice
                    </button>
                    <div id="avatarStyleLicenseText" class="form-text"></div>
                </div>
            </div>
            </div>
            <script>
                var avatarEditorOptions = {{ (current_user.avatar.options|merge_dicts(current_user.avatar.customisations))|tojson }};
                var avatarEditorCSRFName = "{{ config.WTF_CSRF_FIELD_NAME }}";
            </script>
            <form action="{{ url_for('main.avatar') }}" method="POST">
                <input type="hidden" name="{{ config.WTF_CSRF_FIELD_NAME }}" value="{{ csrf_token() }}"/>
                <input type="hidden" name="style"/>
                <input type="hidden" name="seed"/>
                <input type="hidden" name="options"/>
            </form>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="avatarEditorSave">Save changes</button>
            </div>
        </div>
    </div>
</div>