models/challenge.py
import os
import json
import sys
from typing import Optional, Set

from flask_login import current_user

from db import db
from models.solve import Solve


class Challenge:
    def __init__(self, slug: str, name: str, description_html_path: str, category: Optional['ChallengeCategory'] = None, difficulty: Optional[int] = None,):
        self.__slug: str = slug
        self.__name: str = name
        self.__category: Optional['ChallengeCategory'] = category
        self.__difficulty: Optional[int] = difficulty
        self.__description_html_path: str = description_html_path

    @property
    def name(self) -> str:
        return self.__name

    @property
    def slug(self) -> str:
        return self.__slug

    @property
    def category(self) -> Optional['ChallengeCategory']:
        return self.__category

    @staticmethod
    def from_directory(directory: str, category=None) -> 'Challenge':
        if not os.path.isdir(directory) or not os.path.isfile(os.path.join(directory, 'name')):
            raise FileNotFoundError()

        f = open(os.path.join(directory, 'name'), 'r')
        name = f.read()
        f.close()

        description_html_path: str = os.path.abspath(os.path.join(directory, 'description.html'))

        difficulty: Optional[int] = None
        if os.path.isfile(os.path.join(directory, 'difficulty')):
            f = open(os.path.join(directory, 'difficulty'), 'r')
            try:
                difficulty = int(f.read())
                if difficulty > 5 or difficulty < 0:
                    sys.stderr.write(f"Cannot load difficulty for challenge {name}, must be between 0-5. Setting as None")
            except ValueError:
                sys.stderr.write(f"Cannot load difficulty for challenge {name}, it is not an int. Setting as None")
            f.close()

        return Challenge(slug=os.path.split(directory)[-1], name=name, category=category, difficulty=difficulty, description_html_path=description_html_path)

    @property
    def difficulty(self) -> Optional[int]:
        return self.__difficulty

    @property
    def solves(self) -> Set['Solve']:
        # not sure the proper way to do this in sqlalchemy! hybrid properties didn't seem to work!
        return set(s for s in Solve.query.all() if s.challenge == self)

    @property
    def base_points(self) -> int:
        if self.difficulty is None or self.difficulty > 5 or self.difficulty < 0:
            # default 500 points
            return 500
        elif self.difficulty == 0:
            # only for example challenges
            return 100
        elif self.difficulty == 1:
            return 500
        elif self.difficulty == 2:
            return 1000
        elif self.difficulty == 3:
            return 2500
        elif self.difficulty == 4:
            return 3500
        elif self.difficulty == 5:
            return 5000

    @property
    def allow_multiplier(self) -> bool:
        # allow multiplier for all except example challenges
        return self.difficulty != 0

    @property
    def description_html(self) -> Optional[str]:
        if os.path.isfile(self.__description_html_path):
            f = open(self.__description_html_path, 'r')
            html = f.read()
            f.close()
            return html
        return None

auth.py
import base64
import json

from flask import Blueprint, send_from_directory, render_template, redirect, url_for, flash, abort
from flask import current_app as app
from flask_login import login_user, current_user, login_required, logout_user
from flask_wtf import FlaskForm
from wtforms.fields.simple import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Email
import hmac
import hashlib

from models.ctf_platform_app import CTFPlatformApp
from db import db
from models.user import User

app: CTFPlatformApp

auth_blueprint = Blueprint('auth', __name__, url_prefix='/auth')


@auth_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user or user.password != form.password.data:
            flash('Invalid username or password')
            return render_template('login.html', form=form)
        login_user(user)
        return redirect(url_for('main.index'))
    return render_template('login.html', form=LoginForm())


class LoginForm(FlaskForm):
    username = StringField(validators=[DataRequired()])
    password = PasswordField(validators=[DataRequired()])
    remember = BooleanField(default=True)
    submit = SubmitField()


@auth_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@auth_blueprint.route('/register/<string:token>', methods=['GET', 'POST'])
def register(token: str):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    # check register token
    t = json.loads(base64.b64decode(token.encode('utf-8')).decode('utf-8'))
    if not ('email' in t and 'signature' in t):
        abort(400)
    real_signature = hmac.new(app.event.secret_key.encode('utf-8'),
                              msg=t['email'].encode('utf-8'),
                              digestmod=hashlib.sha256
                              ).digest()
    signature = base64.b64decode(t['signature'].encode('utf-8'))
    allow_early_register = len(t['email'].split(';')) == 2 and 'allow_early_register' in t['email'].split(';')[1].split(',')
    if signature != real_signature:
        abort(403)
    if len(User.query.filter_by(email=t['email'].split(';')[0]).all()) > 0:
        abort(410)

    form = RegisterForm()
    if form.validate_on_submit():
        if app.event.has_started is not None and not app.event.has_started and not allow_early_register:
            flash("You can't register until the event starts.")
        else:
            user = User.query.filter_by(username=form.username.data.strip()).first()
            if user or form.username.data.strip().lower() in ['admin']:
                flash('That username is already taken or is not allowed. Please choose another.')
            else:
                user = User(form.username.data, t['email'].split(';')[0], form.password.data, '', 'thumbs', form.username.data, {}, None)
                db.session.add(user)
                db.session.commit()
                return render_template('register.html', register_ok=True, allow_early_register=allow_early_register)

    return render_template('register.html', form=RegisterForm(), email=t['email'].split(';')[0], token=token, register_ok=False, allow_early_register=allow_early_register)


class RegisterForm(FlaskForm):
    username = StringField(validators=[DataRequired()])
    password = PasswordField(validators=[DataRequired()])
    submit = SubmitField()

routes.py
import base64
import json
import mimetypes
import sys
from datetime import datetime, timedelta
from json import JSONDecodeError
from typing import List, Dict, Union

import dicebear.models
# noinspection PyUnresolvedReferences
import pylibmagic  # don't remove, required for cross-platform python-magic support
import magic
import pytz
import requests
import sqlalchemy
from dicebear import DOptions
from flask import Blueprint, send_from_directory, render_template, redirect, url_for, request, abort, Response
from flask import current_app as app
from flask_login import current_user, login_required
from flask_wtf.csrf import generate_csrf
from requests import ReadTimeout
from tzlocal import get_localzone
from werkzeug.exceptions import BadRequest
import hmac
import hashlib

from models.ctf_platform_app import CTFPlatformApp
from db import db
from models.config import Config
from models.orchestration_static import OrchestrationStatic
from models.solve import Solve
from models.team import Team
from models.user import User

app: CTFPlatformApp

main_blueprint = Blueprint('main', __name__)


@main_blueprint.route('/static/<path:path>')
def static(path):
    return send_from_directory('static', path)


@main_blueprint.route('/dashboard')
@login_required
def dashboard():
    latest_solves: List[Solve] = Solve.query.order_by(Solve.when.desc()).limit(15)

    # get values for graph
    team_points: Dict[str, List[Dict[str, Union[str, int]]]] = {}
    teams = Team.query.all()
    for team in teams:
        points: List[Dict[str, Union[str, int]]] = []
        if app.event.start_date is not None and not any(s.when.replace(tzinfo=s.when.tzinfo or get_localzone()) <= app.event.start_date for s in team.solves):
            points.append({
                'when': app.event.start_date.isoformat(),
                'value': 0})
        for solve in sorted(team.solves, key=lambda s: s.when):
            if len(points) == 0:
                points.append({
                    'when': solve.when.isoformat(),
                    'value': solve.points})
            else:
                points.append({
                    'when': solve.when.isoformat(),
                    'value': points[-1]['value'] + solve.points})
        points.append({
            'when': datetime.now().isoformat(),
            'value': team.points})
        team_points[team] = points

    return render_template('dashboard.html', latest_solves=latest_solves, team_points=team_points, teams_ranked=sorted(teams, key=lambda t: t.points, reverse=True))


@main_blueprint.route('/account')
@login_required
def account():
    return render_template('account.html')


@main_blueprint.route('/account/avatar', methods=['POST'])
def avatar():
    if 'style' not in request.form or 'seed' not in request.form or 'options' not in request.form:
        raise BadRequest

    j = {}
    try:
        j = json.loads(request.form['options'])
    except JSONDecodeError:
        raise BadRequest

    current_user.edit_avatar(style=request.form['style'], seed=request.form['seed'], options=j)
    db.session.commit()
    return Response(json.dumps({'avatar': str(current_user.avatar), 'csrf': generate_csrf()}), status=200,
                    mimetype='application/json')


@main_blueprint.route('/')
def index():
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    return redirect(url_for('auth.login'))


@main_blueprint.route('/scope')
@login_required
def scope():
    if app.event.scope_html is None:
        abort(404)
    return render_template('scope.html')


@main_blueprint.route('/team')
@login_required
def team():
    return render_template('team.html', get_solve=lambda t, c: Solve.query.get((t.slug, c.slug)))


@main_blueprint.route('/team/leave', methods=['POST'])
@login_required
def leave_team():
    if current_user.team is None:
        abort(404)
    else:
        old_team = current_user.team
        current_user.team = None
        current_user.team_pending = False
        db.session.commit()
        if len(old_team.users) == 1 and old_team.users[0].team_pending:
            old_team.users[0].team_pending = False
            db.session.commit()
        if current_user.team is not None:
            abort(500)
    return Response(json.dumps({}), status=200, mimetype='application/json')


@main_blueprint.route('/team/reject', methods=['POST'])
@login_required
def team_reject():
    if 'username' not in request.form:
        abort(400)
    if current_user.team is None:
        abort(404)
    if current_user.team_pending:
        abort(403)
    user = User.query.get(request.form['username'])
    if user is None or not user.team_pending:
        abort(404)
    if current_user.team != user.team:
        abort(403)
    user.team = None
    user.team_pending = False
    db.session.commit()
    return Response(json.dumps({}), status=200, mimetype='application/json')


@main_blueprint.route('/team/join', methods=['POST'])
@login_required
def join_team():
    if 'slug' not in request.form:
        abort(400)
    if current_user.team is not None:
        abort(403)
    new_team = Team.query.get(request.form['slug'])
    if new_team is None:
        abort(404)
    current_user.team_pending = len(new_team.users) > 0
    current_user.team = new_team
    db.session.commit()
    return Response(json.dumps({}), status=200, mimetype='application/json')


@main_blueprint.route('/team/join/<string:slug>', methods=['GET'])
@login_required
def join_team_get(slug: str):
    if current_user.team is not None:
        abort(403)
    new_team = Team.query.get(slug)
    if new_team is None:
        abort(404)
    current_user.team_pending = len(new_team.users) > 0
    current_user.team = new_team
    db.session.commit()
    return redirect(url_for('main.team'))


@main_blueprint.route('/team/approve', methods=['POST'])
@login_required
def team_approve():
    if 'username' not in request.form:
        abort(400)
    if current_user.team is None:
        abort(404)
    if current_user.team_pending:
        abort(403)
    user = User.query.get(request.form['username'])
    if user is None or not user.team_pending:
        abort(404)
    if current_user.team != user.team:
        abort(403)
    user.team_pending = False
    db.session.commit()
    return Response(json.dumps({}), status=200, mimetype='application/json')


@main_blueprint.route('/team/create', methods=['POST'])
@login_required
def create_team():
    if 'name' not in request.form:
        abort(400)
    if current_user.team is not None:
        abort(403)
    new_team = Team(name=request.form['name'])
    db.session.add(new_team)
    current_user.team = new_team
    try:
        db.session.commit()
    except sqlalchemy.exc.IntegrityError:
        abort(403)  # not unique
    # begin orchestrate
    config = Config.get_config()
    for challenge in app.event.challenges:
        static_orch = OrchestrationStatic.query.get((new_team.slug, challenge.slug))
        if static_orch is None:
            static_orch = OrchestrationStatic(new_team, challenge)
            db.session.add(static_orch)
            db.session.commit()
        if config.orchestrator_ip is None:
            sys.stderr.write(
                "Cannot deploy {challenge.slug} for {team.slug}: No orchestrator_ip set in config table of DB!\n")
        else:
            url = f"http://{Config.get_config().orchestrator_ip}:{Config.get_config().orchestrator_port}/orchestrate/static"
            try:
                requests.post(
                    url,
                    json={'team': new_team.slug, 'challenge': challenge.slug},
                    timeout=(None, 0.1))
            except ReadTimeout:
                pass
            sys.stderr.write(f"Requested static deploy of {challenge.slug} for {new_team.slug} via {url}\n")
    return Response(json.dumps({}), status=200, mimetype='application/json')


@main_blueprint.route('/team/size')
@login_required
def team_size():
    if current_user.team is None:
        abort(403)
    return str(len(current_user.team.users))


@main_blueprint.route('/challenge/<string:challenge_slug>', methods=['GET', 'POST'])
@login_required
def challenge(challenge_slug: str):
    c = app.event.get_challenge(challenge_slug)
    if c is None:
        abort(404)
    if request.method == 'POST':
        if 'flag' not in request.form:
            abort(400)
        if app.event.has_ended is not None and app.event.has_ended:
            return Response("The event has ended! You can't submit any more flags.", status=403,
                            mimetype='text/plain')
        if current_user.team is None or current_user.team_pending:
            return Response("You need to be accepted onto a team before you can submit flags.", status=403,
                            mimetype='text/plain')
        if current_user.team.has_solved(c):
            return Response("Your team has already solved this flag.", status=410, mimetype='text/plain')
        if app.event.flag_manager.verify_flag(c, current_user.team, request.form['flag']):
            # get multiplier
            solve_position = len(c.solves) + 1
            new_solve = Solve(current_user.team, current_user, c, datetime.now(), Solve.calculate_multiplier(solve_position))
            db.session.add(new_solve)
            db.session.commit()
            return Response(json.dumps({}), status=200, mimetype='application/json')
        return Response("Incorrect flag", status=402, mimetype='text/plain')
    else:
        return render_template('challenge.html', challenge=c,
                               orch_static=OrchestrationStatic.query.get((current_user.team.slug if current_user.team is not None else None, c.slug)),
                               calculate_multiplier=Solve.calculate_multiplier)


@main_blueprint.route('/challenges')
@login_required
def challenges():
    return render_template('challenges.html')


@main_blueprint.route('/logo')
def logo():

templates/challenges.html
{% extends 'base-panel.html' %}

{% block title %}Challenges - {{ super() }}{% endblock %}

{%- do styles.append(url_for('static', filename='assets/extensions/simple-datatables/style.css')) -%}
{%- do styles.append(url_for('static', filename='assets/compiled/css/table-datatable.css')) -%}
{%- do scripts.append(url_for('static', filename='assets/extensions/simple-datatables/umd/simple-datatables.js')) -%}
{%- do scripts.append(url_for('static', filename='assets/challenges.js')) -%}

{% block panel_content %}
<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Challenges</h3>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ url_for('main.dashboard') }}">Dashboard</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Challenges</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<div class="page-content">
    <section class="section">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">
                    Challenges
                </h5>
            </div>
            <div class="card-body">
                <table class="table table-striped table-hover" id="challenges-table">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Category</th>
                            <th>Difficulty</th>
                            <th>Solves</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                    {%- for challenge in event.challenges|sort(attribute='name') -%}
                    {%- set solves = challenge.solves|length -%}
                        <tr onclick="window.location.href='{{ url_for('main.challenge', challenge_slug=challenge.slug) }}'">
                            <td>{{ challenge.name }}</td>
                            <td>{{ (challenge.category.icon or '')|safe }} {{ challenge.category.name }}</td>
                            <td>{%- if challenge.difficulty is none -%} - {%- else -%} {{ challenge.difficulty }} {%- endif -%}</td>
                            <td>{{ solves }} solve{%- if solves != 1 -%}s{%- endif -%}</td>
                            <td>
                            {%- if current_user.team is not none and not current_user.team_pending -%}
                                {%- if current_user.team.has_solved(challenge) -%}
                                <span class="badge bg-success">Solved</span>
                                {%- else -%}
                                <span class="badge bg-danger">Unsolved</span>
                                {%- endif -%}
                            {%- else -%}
                                <span class="badge bg-secondary">No team</span>
                            {%- endif -%}
                            </td>
                        </tr>
                    {%- endfor -%}
                    </tbody>
                </table>
            </div>
        </div>
    </section>
</div>
{% endblock %}

templates/http-error.html
{% extends 'base.html' %}

{% block title %}{{ error.code }} {{ error.name }} - {{ super() }}{% endblock %}

{%- do styles.append(url_for('static', filename='assets/compiled/css/error.css')) -%}'

{% block content %}
    <div id="error">
<div class="error-page container">
    <div class="col-md-8 col-12 offset-md-2">
        <div class="text-center">
        {% if static_file_exists('assets/compiled/svg/error-' + error.code|string +'.svg') %}
            <img class="img-error" src="{{ url_for('static', filename='assets/compiled/svg/error-' + error.code|string + '.svg') }}">
        {% endif %}
            <h1 class="error-title mt-4">{% block error_title %}{{ error.code }} {{ error.name }}{% endblock %}</h1>
            <p class="fs-5 text-gray-600">{% block error_text %}{{ error.description }}{% endblock %}</p>
            <a href="{{ url_for('main.index') }}" class="btn btn-lg btn-outline-primary mt-3">Go Home</a>
        </div>
    </div>
</div>
    </div>
{% endblock %}

templates/team.html
{% extends 'base-panel.html' %}

{% block title %}Team - {{ super() }}{% endblock %}

{%- do styles.append(url_for('static', filename='assets/extensions/sweetalert2/sweetalert2.min.css')) -%}
{%- do scripts.append(url_for('static', filename='assets/extensions/sweetalert2/sweetalert2.min.js')) -%}
{%- do scripts.append(url_for('static', filename='assets/toast.js')) -%}
{%- do pre_content_scripts.append('https://code.jquery.com/jquery-3.7.1.min.js') %}
{%- do scripts.append(url_for('static', filename='assets/team.js')) -%}

{% block panel_content %}
    <div class="page-heading">
        <div class="page-title">
            <div class="row">
                <div class="col-12 col-md-6 order-md-1 order-last">
                    <h3>Team</h3>
                </div>
                <div class="col-12 col-md-6 order-md-2 order-first">
                    <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ url_for('main.dashboard') }}">Dashboard</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Team</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    {%- if current_user.team is none -%}
        <div class="page-content">
            <section class="section">
                <div class="alert alert-warning">
                    You're not in a team. You'll need to join or create a team to take part in challenges.
                </div>
                <div class="row">
                    <div class="col-12 col-lg-4 offset-lg-2">
                        <div class="card">
                            <div class="card-body">
                                <div class="d-flex justify-content-center align-items-center flex-column">
                                    <h3 class="mt-3">Join a Team</h3>
                                    <p class="text-small">
                                        You can join a team that someone else has already created.
                                        You'll need to be approved by somebody who is already on the team.
                                    </p>
                                    <button class="btn btn-primary w-100 join-team">Join Team</button>
                                    <script>
                                        var joinTeamEndpoint = "{{ url_for('main.join_team') }}";
                                        var joinTeamCSRFToken = "{{ csrf_token() }}";
                                        var joinTeamCSRFName = "{{ config.WTF_CSRF_FIELD_NAME }}";
                                    </script>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-lg-4">
                        <div class="card">
                            <div class="card-body">
                                <div class="d-flex justify-content-center align-items-center flex-column">
                                    <h3 class="mt-3">Create a Team</h3>
                                    <p class="text-small">
                                        If you're the first of your team create your team here, but make sure only one person tries to create it to avoid similarly-named duplicates!
                                    </p>
                                    <button class="btn btn-success w-100 create-team">Create Team</button>
                                    <script>
                                        var createTeamEndpoint = "{{ url_for('main.create_team') }}";
                                        var createTeamCSRFToken = "{{ csrf_token() }}";
                                        var createTeamCSRFName = "{{ config.WTF_CSRF_FIELD_NAME }}";
                                    </script>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    {%- else -%}
        <div class="page-content">
            <section class="section">
                {%- if current_user.team_pending -%}
                    <div class="alert alert-warning">You need to be approved by an existing member of the team before
                        you can take part in challenges. They can do this from their team page.
                    </div>
                {%- elif current_user.team.any_pending -%}
                    <div class="alert alert-warning">You have team members waiting to be approved. Please accept or
                        reject them below.
                    </div>
                {%- endif -%}
                <div class="row">
                    <div class="col-12 col-lg-4">
                        <div class="card">
                            <div class="card-body">
                                <div class="d-flex justify-content-center align-items-center flex-column">
                                    <h3 class="mt-3">{{ current_user.team.name }}</h3>
                                    <p class="text-small">
                                        <table class="table">
                                          <tbody>
                                            <tr>
                                              <th scope="row">Total solves</th>
                                              <td>{{ current_user.team.solves|length }}</td>
                                            </tr>
                                            <tr>
                                              <th scope="row">Total points</th>
                                              <td>{{ current_user.team.points }} points</td>
                                            </tr>
                                          </tbody>
                                        </table>
                                    </p>
                                    <button class="btn btn-outline-danger w-100 leave-team">
                                        {%- if current_user.team_pending -%}
                                            Cancel Team Join Request
                                        {%- else -%}
                                            Leave Team
                                        {%- endif -%}
                                    </button>
                                    <script>
                                        var leaveTeamEndpoint = "{{ url_for('main.leave_team') }}";
                                        var teamSizeEndpoint = "{{ url_for('main.team_size') }}";
                                        var leaveTeamCSRFToken = "{{ csrf_token() }}";
                                        var leaveTeamCSRFName = "{{ config.WTF_CSRF_FIELD_NAME }}";
                                    </script>
                                </div>
                            </div>
                        </div>
                        {% include 'widgets/team-members-card.html' %}
                    </div>
                    <div class="col-12 col-lg-8">
                        <div class="card">
                            <div class="card-header">
                                <h4>Solved Challenges</h4>
                            </div>
                            <div class="card-body">
{%- do styles.append(url_for('static', filename='assets/extensions/simple-datatables/style.css')) -%}
{%- do styles.append(url_for('static', filename='assets/compiled/css/table-datatable.css')) -%}
{%- do scripts.append(url_for('static', filename='assets/extensions/simple-datatables/umd/simple-datatables.js')) -%}
{%- do scripts.append(url_for('static', filename='assets/challenges.js')) -%}
                                <table class="table table-striped table-hover" id="challenges-table">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Category</th>
                                            <th>Difficulty</th>
                                            <th>Other Solves</th>
                                            <th>Solved By</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {%- for challenge in current_user.team.solved_challenges|sort(attribute='name') -%}
                                    {%- set solves = challenge.solves|length -%}
                                        <tr onclick="window.location.href='{{ url_for('main.challenge', challenge_slug=challenge.slug) }}'">
                                            <td>{{ challenge.name }}</td>
                                            <td>{{ (challenge.category.icon or '')|safe }} {{ challenge.category.name }}</td>
                                            <td>{%- if challenge.difficulty is none -%} - {%- else -%} {{ challenge.difficulty }} {%- endif -%}</td>
                                            <td>{{ solves - 1 }} solve{%- if solves - 1 != 1 -%}s{%- endif -%}</td>
                                            <td>
                                            {%- set solve = get_solve(current_user.team, challenge) -%}
                                                <div class="d-flex align-items-center">
                                                    {% with size='md', user=solve.user %}
                                                        {% include 'widgets/avatar.html' %}
                                                    {% endwith %}
                                                    <p class="font-bold ms-3 mb-0">{{ solve.user.username }}</p>
                                                </div>
                                            </td>
                                        </tr>
                                    {%- endfor -%}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    {%- endif -%}
{% endblock %}